replicaCount: 1

image:
  tag: "dev"

env:
  springProfilesActive: "dev"
  rateLimitMaxPerHour: "50"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
