{{- if .Values.authService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-platform.fullname" . }}-auth-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: {{ .Values.authService.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.authService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

