apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: order-platform
  labels:
    app: notification-service
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
  selector:
    app: notification-service
