{{- if .Values.inventoryService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-platform.fullname" . }}-inventory-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: inventory
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.inventoryService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

